FROM node:20-alpine
WORKDIR /usr/src/app
ENV GOOGLE_APPLICATION_CREDENTIALS=/app/credentials.json
COPY credentials.json /app/credentials.json

# Install dependencies
COPY package.json pnpm-lock.yaml* ./
RUN corepack enable && pnpm install --frozen-lockfile --prod

# Copy source code
COPY . .

# Build TypeScript sources
RUN pnpm run build
CMD ["pnpm", "run", "serve"]
