version: "3.8"
services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
    depends_on:
      - functions
  functions:
    build:
      context: ./functions
      dockerfile: Dockerfile.functions
    ports:
      - "5001:5001"
    environment:
      - FUNCTIONS_EMULATOR=true
networks:
  default:
    driver: bridge
